In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import linear_model

In [ ]:
df = pd.read_csv('hiring.csv')

In [ ]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [ ]:
df.experience.isna().sum()

2

In [ ]:
df.experience = df.experience.fillna('zero')

In [ ]:
import math
mean_test_score = math.floor(df['test_score(out of 10)'].mean())
df['test_score(out of 10)'] = df['test_score(out of 10)'].fillna(mean_test_score)

In [ ]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    7.0                           7      72000
7     eleven                    7.0                           8      80000

In [ ]:
# To convert word to number

!pip install word2number
from word2number import w2n # Import the w2n module

df['experience'] = df['experience'].astype(str).apply(lambda x: w2n.word_to_num(x) if x.lower() != 'nan' else np.nan)

  Preparing metadata (setup.py) ... done
  Created wheel for word2number: filename=word2number-1.1-py3-none-any.whl size=5568 sha256=c735e197cd4dddde5e96a2e16aba3b284e9046f611de64ffaf854e86b2101c1d
  Stored in directory: /root/.cache/pip/wheels/84/ff/26/d3cfbd971e96c5aa3737ecfced81628830d7359b55fbb8ca3b
Successfully built word2number


In [ ]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    7.0                           7      72000
7          11                    7.0                           8      80000

In [ ]:
model_linear = linear_model.LinearRegression()
model_linear.fit(df[['experience', 'test_score(out of 10)', 'interview_score(out of 10)']], df['salary($)'])

LinearRegression()

In [ ]:
model_linear.coef_

array([2922.26901502, 2221.30909959, 2147.48256637])

In [ ]:
model_linear.intercept_

14992.65144669314

In [ ]:
model_linear.predict([[2, 9, 6]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([53713.86677124])

In [ ]:
model_linear.predict([[12, 10, 10]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([93747.79628651])

In [ ]:
# Saving the file into pickle
import pickle
with open('model_pickle', 'wb') as f:
    pickle.dump(model_linear, f)

In [ ]:
with open('model_pickle', 'rb') as f:
    mp = pickle.load(f)

In [ ]:
mp.predict([[2, 9, 6]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([53713.86677124])

In [ ]:
# Saving model using joblib
! pip install joblib
import joblib
joblib.dump(model_linear, 'model_joblib')


['model_joblib']

In [ ]:
mj = joblib.load('model_joblib')

In [ ]:
mj.predict([[2, 9, 6]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([53713.86677124])

In [ ]:
mj.coef_

array([2922.26901502, 2221.30909959, 2147.48256637])

In [ ]:
mj.intercept_

14992.65144669314